services:
  mongo:
    image: mongo:7.0
    container_name: learn_spring_mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"
    volumes:
      - "./init-data.js:/docker-entrypoint-initdb.d/init-data.js:ro"