CREATE DATABASE batchdb;

\c batchdb
CREATE TABLE BATCH_STEP_EXECUTION_ADDITIONAL_DATA (
    STEP_EXECUTION_ID INT8 NOT NULL PRIMARY KEY,
    STEP_NUMBER INT NOT NULL,
    TASK_NUMBER INT NOT NULL,
    TASK_NAME VARCHAR(200) NOT NULL
);
