CREATE DATABASE batchdb;

\c batchdb
CREATE TABLE BATCH_STEP_EXECUTION_ADDITIONAL_DATA (
    STEP_EXECUTION_ID INT8 NOT NULL PRIMARY KEY,
    STEP_NUMBER INT8 NOT NULL,
    ALT_TASK_NAME VARCHAR(200) NOT NULL
);
