services:
  mongo:
    image: mongo:7.0
    command: [ "--replSet", "rs0", "--bind_ip_all", "--port", "27017" ]
    ports:
      - 27017:27017
    networks:
      - mongonet
  mongo-init:
    image: mongo:7.0
    depends_on:
      - mongo
    networks:
      - mongonet
    environment:
      - MONGO_INITDB_USERNAME=app_user
      - MONGO_INITDB_PASSWORD=app_password
    volumes:
      - "./docker/mongo/:/data/init/"
    entrypoint:
      - "/data/init/init.sh"

networks:
  mongonet:
